---
name: 'Pull Request to GitHub'

on:
  push: 
    branches: 
      - master

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Running date command'
        run: date
        
      - name: 'Getting OS details'
        run: cat /etc/os-release

      - name: 'Current working directory and its contents'
        run: |-
          pwd
          ls -l
       
